FROM nvcr.io/nvidia/pytorch:25.01-py3

WORKDIR /workspace/app

COPY requirements.txt .
COPY requirements_cpu.txt .

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

COPY . .

# Commment this if you want to experiment
CMD ["python3", "main.py", "test", "--model_path", "./results/last_checkpoint.pth"]