
services:
  uxo-api:
    build:
      context: .
      dockerfile: dockerfile_api
    container_name: uxo-api
    restart: unless-stopped
    command: python3 deploy/runAPI.py --model_path ./results/best_checkpoint.pth --input_size 800 --host 0.0.0.0 --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace/app
    volumes:
      - ./:/workspace/app
      - ./results:/workspace/app/results
      - ./logs:/workspace/app/logs
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
